import type {jsPDF as JsPDFDoc} from 'jspdf';
import type {BusbarCalculationResult, BusbarInput} from '../domain/types';
import {formatNumber, statusLabel} from '../utils/format';
import type {CapturedImage} from './captureSvg';

export type PdfReportExtras = {
  crossSection?: CapturedImage;
  forecast?: CapturedImage;
  shortCircuit?: CapturedImage;
};

const disclaimer =
  'This report was generated by CAD AutoScript Busbar Calculator as an engineering aid. It does not replace licensed standards, manufacturer design verification, IEC 61439 assembly verification, short-circuit type tests, local electrical regulations, or review by a qualified electrical engineer. Values marked as estimated or example-only must not be used for final design release without validation.';

function line(doc: JsPDFDoc, y: number) {
  doc.setDrawColor(180, 190, 205);
  doc.line(14, y, 196, y);
}

function title(doc: JsPDFDoc, text: string, y: number) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(text, 14, y);
  line(doc, y + 4);
}

function table(doc: JsPDFDoc, rows: Array<[string, string]>, x: number, y: number, width = 86) {
  doc.setFontSize(9);
  rows.forEach(([label, value], index) => {
    const rowY = y + index * 7;
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 90, 105);
    doc.text(label, x, rowY);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(20, 30, 45);
    doc.text(value, x + width * 0.58, rowY, {maxWidth: width * 0.42});
  });
  doc.setTextColor(20, 30, 45);
}

function footer(doc: JsPDFDoc, result: BusbarCalculationResult, page: number) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(95, 105, 120);
  doc.text(`Busbar Calculator | Engine v${result.engineVersion} | Page ${page}`, 14, 287);
}

function addImagePage(doc: JsPDFDoc, label: string, image: CapturedImage, result: BusbarCalculationResult) {
  doc.addPage();
  title(doc, label, 18);
  const maxWidth = 180;
  const maxHeight = 230;
  const aspect = image.height / image.width;
  let drawWidth = maxWidth;
  let drawHeight = drawWidth * aspect;
  if (drawHeight > maxHeight) {
    drawHeight = maxHeight;
    drawWidth = drawHeight / aspect;
  }
  const x = (210 - drawWidth) / 2;
  doc.addImage(image.dataUrl, image.format, x, 30, drawWidth, drawHeight, undefined, 'FAST');
  footer(doc, result, doc.getNumberOfPages());
}

export async function buildPdfReport(
  input: BusbarInput,
  result: BusbarCalculationResult,
  extras: PdfReportExtras = {},
): Promise<Blob> {
  const {jsPDF} = await import('jspdf');
  const doc = new jsPDF({orientation: 'portrait', unit: 'mm', format: 'a4', compress: true});
  doc.setProperties({
    title: `Busbar report ${input.project.tag}`,
    subject: 'Busbar Calculator engineering report',
    creator: 'CAD AutoScript Busbar Calculator',
  });

  title(doc, 'Busbar Calculator Report', 18);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(`${input.project.projectName} / ${input.project.tag}`, 14, 34);
  doc.setFontSize(11);
  doc.setTextColor(result.status === 'fail' ? 180 : result.status === 'warn' ? 170 : 0, result.status === 'pass' ? 130 : 80, 55);
  doc.text(`Overall status: ${statusLabel(result.status).toUpperCase()}`, 14, 43);
  doc.setTextColor(20, 30, 45);

  table(
    doc,
    [
      ['Panel', input.project.panelName],
      ['Revision', input.project.revision],
      ['Engineer', input.project.engineer],
      ['Date', input.project.date],
      ['System', `${input.systemType} ${input.phaseMode}`],
      ['Voltage', `${formatNumber(input.ratedVoltage_V, 0)} V`],
      ['Current', `${formatNumber(input.ratedCurrent_A, 0)} A`],
    ],
    14,
    58,
  );

  table(
    doc,
    [
      ['Selected busbar', `${result.selectedProfile.materialLabel} ${result.selectedProfile.width_mm} x ${result.selectedProfile.thickness_mm} mm`],
      ['Bars per phase', String(result.selectedProfile.barsPerPhase)],
      ['Area per phase', `${formatNumber(result.selectedProfile.areaPerPhase_mm2, 0)} mm²`],
      ['Current density', `${formatNumber(result.electrical.currentDensity_A_per_mm2, 2)} A/mm²`],
      ['Losses per meter', `${formatNumber(result.electrical.losses_W_per_m, 1)} W/m`],
      ['Steady temperature', `${formatNumber(result.thermal.steadyStateTemp_C, 1)} °C`],
      ['Channel envelope', `${formatNumber(result.envelope.width_mm, 1)} x ${formatNumber(result.envelope.height_mm, 1)} mm`],
    ],
    108,
    58,
  );

  title(doc, 'Warnings', 116);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  let y = 128;
  result.warnings.slice(0, 8).forEach((warning) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${warning.severity.toUpperCase()}: ${warning.code}`, 14, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.text(warning.message, 14, y, {maxWidth: 180});
    y += 9;
  });

  title(doc, 'Engineering Disclaimer', 226);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(disclaimer, 14, 238, {maxWidth: 180});
  footer(doc, result, 1);

  if (extras.crossSection) {
    addImagePage(doc, 'Busbar Cross-section', extras.crossSection, result);
  }
  if (extras.forecast) {
    addImagePage(doc, 'Temperature Forecast', extras.forecast, result);
  }
  if (extras.shortCircuit) {
    addImagePage(doc, 'Short-circuit Force & Supports', extras.shortCircuit, result);
  }

  doc.addPage();
  title(doc, 'Calculation Trace', 18);
  y = 32;
  result.trace.forEach((item, index) => {
    if (y > 262) {
      footer(doc, result, doc.getNumberOfPages());
      doc.addPage();
      title(doc, 'Calculation Trace', 18);
      y = 32;
    }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`${index + 1}. ${item.label}`, 14, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    y += 5;
    doc.text(`Method: ${item.method}`, 18, y);
    y += 5;
    if (item.equation) {
      doc.text(`Equation: ${item.equation}`, 18, y);
      y += 5;
    }
    doc.text(`Output: ${item.output}${item.unit ? ` ${item.unit}` : ''}`, 18, y);
    y += 8;
  });
  footer(doc, result, doc.getNumberOfPages());

  doc.addPage();
  title(doc, 'Candidate Comparison', 18);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('Rank', 14, 32);
  doc.text('Profile', 30, 32);
  doc.text('Bars', 64, 32);
  doc.text('Area', 82, 32);
  doc.text('J', 108, 32);
  doc.text('Temp', 132, 32);
  doc.text('Envelope', 156, 32);
  doc.text('Status', 186, 32);
  doc.setFont('helvetica', 'normal');
  result.candidates.slice(0, 12).forEach((candidate, index) => {
    const rowY = 40 + index * 8;
    doc.text(String(candidate.rank), 14, rowY);
    doc.text(`${candidate.width_mm} x ${candidate.thickness_mm}`, 30, rowY);
    doc.text(String(candidate.barsPerPhase), 64, rowY);
    doc.text(formatNumber(candidate.areaPerPhase_mm2, 0), 82, rowY);
    doc.text(formatNumber(candidate.currentDensity_A_per_mm2, 2), 108, rowY);
    doc.text(formatNumber(candidate.steadyStateTemp_C, 1), 132, rowY);
    doc.text(`${formatNumber(candidate.channelWidth_mm, 0)} x ${formatNumber(candidate.channelHeight_mm, 0)}`, 156, rowY);
    doc.text(statusLabel(candidate.status), 186, rowY);
  });
  footer(doc, result, doc.getNumberOfPages());

  return doc.output('blob');
}

export function reportFileName(input: BusbarInput): string {
  const safeTag = (input.project.tag || input.project.projectName || 'project')
    .replace(/[^a-z0-9-_]+/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return `busbar-report_${safeTag}_${Math.round(input.ratedCurrent_A)}A_${Math.round(input.ratedVoltage_V)}V_${input.project.date}_rev${input.project.revision}.pdf`;
}
